import boto3
import json
from IPython.display import JSON

# Create a Bedrock client
#bedrock_client = boto3.client('bedrock')

# Define the model ID and input parameters - see Bedrock documentation for details on input format
#model_id = 'amazon.titan-1'

#setting up a model ID 
MODEL_ID = "amazon.nova-lite-v1:0"  #each model has a unique identifier, which you can find in the Bedrock documentation or console. This ID is used to specify which model you want to invoke when making API calls.   
#create bedrock run-time client
bedrock = boto3.client(service_name='bedrock-runtime', region_name='us-east-1')
#The runtime client is used to interact with the Bedrock service for invoking models and handling responses. You can specify the region where your Bedrock models are hosted, such as 'us-east-1' or 'us-west-2'.   
#When invoking a model, you typically need to provide the model ID and the input parameters in a specific format. The input parameters can vary depending on the model you are using, but they often include a prompt or query that you want the model to process. For example, if you are using a language model, your input might be a text prompt that you want the model to complete or respond to. 
#The response from the model will usually be in a structured format, such as JSON, which you can parse and use in your application. The exact structure of the response will depend on the model and the input you provided. You can refer to the Bedrock documentation for details on how to format your input and interpret the responses for different models.   
#Here is an example of how you might invoke a model using the Bedrock runtime client:
#The input parameters for the model will depend on the specific model you are using and the task you want to perform. For example, if you are using a language model, your input might be a text prompt that you want the model to complete or respond to. The input parameters are typically provided in a JSON format, which can include various fields such as "prompt", "maxTokens", "temperature", etc., depending on the model's requirements. You can refer to the Bedrock documentation for details on the specific input parameters needed for each model. 
#When you invoke the model, you will receive a response that contains the output generated by the model based on your input parameters. The response is usually in a structured format, such as JSON, which you can parse and use in your application. The exact structure of the response will depend on the model and the input you provided. You can refer to the Bedrock documentation for details on how to interpret the responses for different models.  
#The runtime API allows you to interact with the Bedrock service to invoke models and handle responses. You can specify the model ID and input parameters when making API calls, and the response will contain the output generated by the model based on your input. The exact format of the input and response will depend on the specific model you are using, so it's important to refer to the Bedrock documentation for details on how to format your input and interpret the responses for different models. 
#The runtime API is designed to provide a seamless way to interact with the Bedrock service, allowing you to easily invoke models and handle responses in your applications. You can use the runtime client to send requests to the Bedrock service, specifying the model ID and input parameters, and then process the responses to extract the information you need. The runtime API abstracts away the complexities of interacting with the underlying infrastructure, making it easier for developers to integrate Bedrock models into their applications.  
#When invoking a model using the Bedrock runtime API, you typically need to provide the model ID and the input parameters in a specific format. The input parameters can vary depending on the model you are using, but they often include a prompt or query that you want the model to process. For example, if you are using a language model, your input might be a text prompt that you want the model to complete or respond to. The response from the model will usually be in a structured format, such as JSON, which you can parse and use in your application. The exact structure of the response will depend on the model and the input you provided. You can refer to the Bedrock documentation for details on how to format your input and interpret the responses for different models.  
#The runtime APIs are the data plane APIs where we can make inference requests against models in Bedrock.we can use invoke_model API to make inference requests to the model. The input parameters for the model will depend on the specific model you are using and the task you want to perform. For example, if you are using a language model, your input might be a text prompt that you want the model to complete or respond to. The input parameters are typically provided in a JSON format, which can include various fields such as "prompt", "maxTokens", "temperature", etc., depending on the model's requirements. You can refer to the Bedrock documentation for details on the specific input parameters needed for each model. When you invoke the model, you will receive a response that contains the output generated by the model based on your input parameters. The response is usually in a structured format, such as JSON, which you can parse and use in your application. The exact structure of the response will depend on the model and the input you provided. You can refer to the Bedrock documentation for details on how to interpret the responses for different models.  


# Define the input parameters for the model
#input_parameters = {
#    "input": "What is the capital of France?"
#}

response = bedrock.invoke_model(
    modelId=MODEL_ID,
    body=json.dumps({
        "schemaVersion": "messages-v1",
        "messages": [
            {
                "role": "user",
                "content": [
                    {
                        "text": "Rewrite this sentence for me in a formal tone: What time can you do lunch tomorrow?"}]}],
                        "inferenceConfig": {"maxTokens": 500, "topK": 20, "temperature": 0.7}
    })
)

JSON(json.loads(response['body'].read().decode()), expanded=True)

